
package model.filestorage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileStorageService", targetNamespace = "http://fileStorage.model/", wsdlLocation = "http://localhost:8080/QSIS-Model-Module-Macro-Service-Impl/?wsdl")
public class FileStorageService
    extends Service
{

    private final static URL FILESTORAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESTORAGESERVICE_EXCEPTION;
    private final static QName FILESTORAGESERVICE_QNAME = new QName("http://fileStorage.model/", "FileStorageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/QSIS-Model-Module-Macro-Service-Impl/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESTORAGESERVICE_WSDL_LOCATION = url;
        FILESTORAGESERVICE_EXCEPTION = e;
    }

    public FileStorageService() {
        super(__getWsdlLocation(), FILESTORAGESERVICE_QNAME);
    }

    public FileStorageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESTORAGESERVICE_QNAME, features);
    }

    public FileStorageService(URL wsdlLocation) {
        super(wsdlLocation, FILESTORAGESERVICE_QNAME);
    }

    public FileStorageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESTORAGESERVICE_QNAME, features);
    }

    public FileStorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileStorageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "FileStoragePort")
    public Storage getFileStoragePort() {
        return super.getPort(new QName("http://fileStorage.model/", "FileStoragePort"), Storage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "FileStoragePort")
    public Storage getFileStoragePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fileStorage.model/", "FileStoragePort"), Storage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESTORAGESERVICE_EXCEPTION!= null) {
            throw FILESTORAGESERVICE_EXCEPTION;
        }
        return FILESTORAGESERVICE_WSDL_LOCATION;
    }

}
